### ISSUE TITLE
update PIP

### ISSUE THREAD

**Issue by kevthehermit** [crackinglandia/pype32#13] opened 2015-07-26 20:23 UTC
Since the changes to the net parser the old version of pype32 is not compatible with my scripts. 

The new version is not on pip so anyone installing from there can not use my code base.

**Comment by piazzamp** [comment] 2015-09-09 19:52
same goes for the one [release](https://github.com/crackinglandia/pype32/releases) in this repo

**Comment by ghost** [comment] 2015-09-10 00:19
Please update the official release as noted by piazzamp as well as the version installed via pip. They are older versions.

**Comment by crackinglandia** [comment] 2015-10-27 00:19
I have generated a new release (v0.1-alpha5) which is available from https://github.com/crackinglandia/pype32/releases with the latest changes from master but I'm having troubles uploading the package to pip. I'll try later again (I messed up doing the update and I think I broke something, pip doesn't let me edit the packages again).

**Comment by crackinglandia** [comment] 2015-10-27 01:24
Mmm when using PIP 1.5.6, new version of pype32 is not installed. PIP keeps installing older version. 

If I upgrade PIP to the latest version (current is 7.1.2) using "pip install -U pip" then it gets the latest version of pype32 (0.1-alpha5). 

Does anyone have idea about how to solve this problem?. I don't want to force the user to upgrade its PIP version. I need help on this.

**Comment by poxyran** [comment] 2015-10-27 14:35
Well, it seems that the problem is on PyPi and the versioning system it has. I uploaded 0.1-alpha4 and then v0.1-alpha5. Older versions of PIP can't decide right what version of the package will be installed. Newer versions have a more complex comparison method to avoid this situations where package names have a slight difference. 

The easiest solution here is to delete the old package (alpha4) and keep only alpha5.

**Comment by crackinglandia** [comment] 2015-10-27 16:35
Ready!. Try it now.

I'm closing this one. Reopen if needed.

**Closed as completed by crackinglandia** 2015-10-27 16:35 UTC

**Comment by kevthehermit** [comment] 2015-10-29 15:28
Still having issues with pip Using the version that comes with ubuntu via a `sudo apt-get install python-pip`

```
localadmin@tech-malware:~/viperv2$ pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

```

```
Downloading/unpacking pype32
  Could not find a version that satisfies the requirement pype32 (from versions: v0.1-alpha5)
Cleaning up...
No distributions matching the version for pype32
Storing debug log for failure in /home/localadmin/.pip/pip.log
localadmin@tech-malware:~/viperv2$ 

```

If i manually install the latest version then all works as expected

```
localadmin@tech-malware:/tmp$ pip -V
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

```

```
  Downloading pype32-v0.1-alpha5.zip (1.5MB)
    100% |████████████████████████████████| 1.5MB 203kB/s 
Installing collected packages: pype32
  Running setup.py install for pype32
Successfully installed pype32-0.1a5

```

**Comment by poxyran** [comment] 2015-10-29 15:39
Have you tried "sudo pip install --pre pype32"?

**Comment by poxyran** [comment] 2015-10-29 15:52
I did a test on a fresh Ubuntu 12.04 installation:

fastix@ubuntu:~$ uname -a
Linux ubuntu 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

fastix@ubuntu:~$ pip --version
pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)

pip 1.0 doesn't have the "--pre" option but it works OK:

fastix@ubuntu:~$ sudo pip install --pre pype32
Usage: /usr/bin/pip install [OPTIONS] PACKAGE_NAMES...

/usr/bin/pip install: error: no such option: --pre

fastix@ubuntu:~$ sudo pip install  pype32
Downloading/unpacking pype32
  Downloading pype32-v0.1-alpha5.zip (1.5Mb): 1.5Mb downloaded
  Running setup.py egg_info for package pype32
    /home/fastix/build/pype32/setup.py:76: UserWarning: README file not found or unreadable!
      warn("README file not found or unreadable!")

```
warning: no files found matching 'README'
```

Installing collected packages: pype32
  Running setup.py install for pype32
    /home/fastix/build/pype32/setup.py:76: UserWarning: README file not found or unreadable!
      warn("README file not found or unreadable!")
    changing mode of build/scripts-2.7/readpe.py from 644 to 755

```
warning: no files found matching 'README'
changing mode of /usr/local/bin/readpe.py to 755
```

Successfully installed pype32
Cleaning up...

fastix@ubuntu:~$ python
Python 2.7.3 (default, Apr 20 2012, 22:39:59) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pype32
> > > dir(pype32)
> > > ['AlignedString', 'Array', 'ArrayTypeException', 'BYTE', 'DWORD', 'DataDirectory', 'DataLengthException', 'DataMismatchException', 'Directory', 'DirectoryEntriesLengthException', 'DirectoryEntryException', 'DosHeader', 'ExportTable', 'ExportTableEntry', 'FileHeader', 'ImageBaseRelocation', 'ImageBaseRelocationEntry', 'ImageBoundForwarderRef', 'ImageBoundForwarderRefEntry', 'ImageBoundImportDescriptor', 'ImageBoundImportDescriptorEntry', 'ImageDebugDirectories', 'ImageDebugDirectory', 'ImageExportTable', 'ImageImportDescriptor', 'ImageImportDescriptorEntry', 'ImageImportDescriptorMetaData', 'ImageLoadConfigDirectory', 'ImageLoadConfigDirectory64', 'ImportAddressTable', 'ImportAddressTableEntry', 'ImportAddressTableEntry64', 'InstanceErrorException', 'InvalidParameterException', 'NETDirectory', 'NetDirectory', 'NetMetaDataHeader', 'NetMetaDataStreamEntry', 'NetMetaDataStreams', 'NetMetaDataTableHeader', 'NetMetaDataTables', 'NetResources', 'NotValidPathException', 'NtHeaders', 'OptionalHeader', 'OptionalHeader64', 'PE', 'PEException', 'PEWarning', 'PyPe32Exception', 'PyPe32Warning', 'QWORD', 'ReadData', 'ReadDataOffsetException', 'SectionHeader', 'SectionHeaders', 'SectionHeadersException', 'Sections', 'String', 'TLSDirectory', 'TLSDirectory64', 'TypeNotSupportedException', 'WORD', 'WriteData', 'WriteDataOffsetException', 'WrongOffsetValueException', '**all**', '**builtins**', '**doc**', '**file**', '**name**', '**package**', '**path**', '**revision**', 'baseclasses', 'caching', 'consts', 'datadirs', 'datatypes', 'directories', 'dotnet', 'excep', 'pype32', 'utils', 'version', 'version_number']
